#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
export EXP_NAME="${EXP_NAME:-sf_maca_4060_overnight_${RUN_ID}}"

export DEVICE="${DEVICE:-gpu}"
export TOTAL_ENV_STEPS="${TOTAL_ENV_STEPS:-120000000}"
export MIN_PHASE_ENV_STEP_HEADROOM="${MIN_PHASE_ENV_STEP_HEADROOM:-4000000}"

export PHASE1_SECONDS="${PHASE1_SECONDS:-300}"
export PHASE2_CYCLES="${PHASE2_CYCLES:-0}"
export PHASE2_PULSE_SECONDS="${PHASE2_PULSE_SECONDS:-0}"
export PHASE2_MAIN_SECONDS="${PHASE2_MAIN_SECONDS:-0}"
export PHASE3_SECONDS="${PHASE3_SECONDS:-28500}"

export NUM_WORKERS="${NUM_WORKERS:-10}"
export NUM_ENVS_PER_WORKER="${NUM_ENVS_PER_WORKER:-1}"
export ROLLOUT="${ROLLOUT:-64}"
export RECURRENCE="${RECURRENCE:-64}"
export BATCH_SIZE="${BATCH_SIZE:-6400}"
export PPO_EPOCHS="${PPO_EPOCHS:-4}"
export HIDDEN_SIZE="${HIDDEN_SIZE:-256}"
export LEARNER_MAIN_LOOP_NUM_CORES="${LEARNER_MAIN_LOOP_NUM_CORES:-3}"
export TRAJ_BUFFERS_EXCESS_RATIO="${TRAJ_BUFFERS_EXCESS_RATIO:-4.0}"
export MAX_POLICY_LAG="${MAX_POLICY_LAG:-12}"
export SAVE_EVERY_SEC="${SAVE_EVERY_SEC:-900}"
export KEEP_CHECKPOINTS="${KEEP_CHECKPOINTS:-12}"
export TRAIN_IN_BACKGROUND_THREAD="${TRAIN_IN_BACKGROUND_THREAD:-False}"

exec bash scripts/run_sf_maca_radar_support_8h_curriculum.sh "$@"
