#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export MACA_EXTENDED_OBSERVATION="${MACA_EXTENDED_OBSERVATION:-True}"
export MACA_DECOUPLED_ACTION_HEADS="${MACA_DECOUPLED_ACTION_HEADS:-True}"
export MACA_ADAPTIVE_SUPPORT_POLICY="${MACA_ADAPTIVE_SUPPORT_POLICY:-True}"
export MACA_SUPPORT_SEARCH_HOLD="${MACA_SUPPORT_SEARCH_HOLD:-6}"
export MACA_RADAR_TRACKING_OBSERVATION="${MACA_RADAR_TRACKING_OBSERVATION:-True}"
export MACA_TRACK_MEMORY_STEPS="${MACA_TRACK_MEMORY_STEPS:-12}"
export MACA_SEMANTIC_SCREEN_OBSERVATION="${MACA_SEMANTIC_SCREEN_OBSERVATION:-True}"
export MACA_SCREEN_TRACK_MEMORY_STEPS="${MACA_SCREEN_TRACK_MEMORY_STEPS:-12}"

exec bash scripts/run_sf_maca_decoupled_8h_curriculum.sh "$@"
