#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

EXP_NAME="${EXP_NAME:-sf_maca_recovery_20260412_163435}"
RUN_ID="$(date '+%Y%m%d_%H%M%S')"
RUN_TAG="${RUN_TAG:-${EXP_NAME}_takeover_night_${RUN_ID}}"

# Overnight default: 11h continuation on the same experiment (resume-only).
TAKEOVER_DURATION_SECONDS="${TAKEOVER_DURATION_SECONDS:-39600}"

export EXP_NAME
export RUN_TAG
export VALIDATION_DURATION_SECONDS="${VALIDATION_DURATION_SECONDS:-$TAKEOVER_DURATION_SECONDS}"
export TRAIN_FOR_ENV_STEPS="${TRAIN_FOR_ENV_STEPS:-420000000}"
export REQUIRED_ENV_STEPS_HEADROOM="${REQUIRED_ENV_STEPS_HEADROOM:-60000000}"
export MIN_ENV_STEP_DELTA="${MIN_ENV_STEP_DELTA:-200000}"
export POST_EVAL_EPISODES="${POST_EVAL_EPISODES:-30}"
export MONITOR_INTERVAL_SEC="${MONITOR_INTERVAL_SEC:-1800}"
export MONITOR_EVAL_EPISODES="${MONITOR_EVAL_EPISODES:-5}"

export NUM_WORKERS="${NUM_WORKERS:-10}"
export NUM_ENVS_PER_WORKER="${NUM_ENVS_PER_WORKER:-1}"
export ROLLOUT="${ROLLOUT:-64}"
export RECURRENCE="${RECURRENCE:-64}"
export BATCH_SIZE="${BATCH_SIZE:-6400}"
export PPO_EPOCHS="${PPO_EPOCHS:-4}"
export HIDDEN_SIZE="${HIDDEN_SIZE:-256}"
export LEARNING_RATE="${LEARNING_RATE:-1e-4}"
export GAMMA="${GAMMA:-0.999}"
export REWARD_SCALE="${REWARD_SCALE:-0.002}"
export REWARD_CLIP="${REWARD_CLIP:-50.0}"
export EXPLORATION_LOSS_COEFF="${EXPLORATION_LOSS_COEFF:-0.06}"
export MAX_POLICY_LAG="${MAX_POLICY_LAG:-12}"
export KEEP_CHECKPOINTS="${KEEP_CHECKPOINTS:-16}"
export SAVE_EVERY_SEC="${SAVE_EVERY_SEC:-900}"
export TRAIN_IN_BACKGROUND_THREAD="${TRAIN_IN_BACKGROUND_THREAD:-False}"
export LEARNER_MAIN_LOOP_NUM_CORES="${LEARNER_MAIN_LOOP_NUM_CORES:-3}"
export TRAJ_BUFFERS_EXCESS_RATIO="${TRAJ_BUFFERS_EXCESS_RATIO:-4.0}"

export MACA_ENABLE_SF_BUFFER_SQUEEZE_PATCH="${MACA_ENABLE_SF_BUFFER_SQUEEZE_PATCH:-0}"
export MACA_REWARD_RADAR_FIGHTER_DETECTOR="${MACA_REWARD_RADAR_FIGHTER_DETECTOR:-8}"
export MACA_REWARD_RADAR_FIGHTER_FIGHTER="${MACA_REWARD_RADAR_FIGHTER_FIGHTER:-8}"
export MACA_REWARD_STRIKE_FIGHTER_SUCCESS="${MACA_REWARD_STRIKE_FIGHTER_SUCCESS:-1200}"
export MACA_REWARD_STRIKE_FIGHTER_FAIL="${MACA_REWARD_STRIKE_FIGHTER_FAIL:--2}"
export MACA_REWARD_STRIKE_ACT_VALID="${MACA_REWARD_STRIKE_ACT_VALID:-40}"
export MACA_REWARD_KEEP_ALIVE_STEP="${MACA_REWARD_KEEP_ALIVE_STEP:--2}"
export MACA_REWARD_DRAW="${MACA_REWARD_DRAW:--2000}"
export MACA_MISSED_ATTACK_PENALTY="${MACA_MISSED_ATTACK_PENALTY:-60}"

# Training-only behavior prior: enforce a minimum probability mass for valid
# fire actions whenever attack opportunities exist. This is a targeted rescue
# against policy collapse to deterministic no-fire.
export MACA_FIRE_LOGIT_BIAS="${MACA_FIRE_LOGIT_BIAS:-0.0}"
export MACA_FIRE_PROB_FLOOR="${MACA_FIRE_PROB_FLOOR:-0.03}"
# Keep eval unbiased by default. Set >0 only for ablation checks.
export MACA_EVAL_FIRE_PROB_FLOOR="${MACA_EVAL_FIRE_PROB_FLOOR:-0.0}"

export MACA_AUTO_EVAL_LOW_FIRE_THRESHOLD="${MACA_AUTO_EVAL_LOW_FIRE_THRESHOLD:-0.003}"
export MACA_AUTO_EVAL_MAX_LOW_FIRE_STREAK="${MACA_AUTO_EVAL_MAX_LOW_FIRE_STREAK:-4}"
export MACA_AUTO_EVAL_MIN_FIRE_OPP_RATIO="${MACA_AUTO_EVAL_MIN_FIRE_OPP_RATIO:-0.01}"
export MACA_AUTO_EVAL_MAX_LOW_RATIO_STREAK="${MACA_AUTO_EVAL_MAX_LOW_RATIO_STREAK:-4}"
export MACA_AUTO_EVAL_MIN_OPPORTUNITY_FOR_RATIO="${MACA_AUTO_EVAL_MIN_OPPORTUNITY_FOR_RATIO:-0.35}"
export MACA_AUTO_EVAL_ANOMALY_FIRE_THRESHOLD="${MACA_AUTO_EVAL_ANOMALY_FIRE_THRESHOLD:-0.003}"

exec bash scripts/run_sf_maca_recovery_validation.sh
